language: python
sudo: false
cache: pip

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install -r requirements.txt -r test-requirements.txt
  # - pip install coveralls

script:
  - py.test
  - flake8

# after_success:
#   - coveralls

notifications:
  email:
    - nineseconds@yandex.ru
